2022-02-25 17:15:42,909 INFO    MainThread:706021 [internal.py:wandb_internal():89] W&B internal server running at pid: 706021, started at: 2022-02-25 17:15:42.908856
2022-02-25 17:15:42,910 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: check_version
2022-02-25 17:15:42,910 INFO    WriterThread:706021 [datastore.py:open_for_write():77] open: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/run-yk2pvfyd.wandb
2022-02-25 17:15:42,911 DEBUG   SenderThread:706021 [sender.py:send():235] send: header
2022-02-25 17:15:42,911 DEBUG   SenderThread:706021 [sender.py:send_request():249] send_request: check_version
2022-02-25 17:15:42,947 DEBUG   SenderThread:706021 [sender.py:send():235] send: run
2022-02-25 17:15:43,255 INFO    SenderThread:706021 [dir_watcher.py:__init__():169] watching files in: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files
2022-02-25 17:15:43,255 INFO    SenderThread:706021 [sender.py:_start_run_threads():809] run started: yk2pvfyd with start time 1645789542
2022-02-25 17:15:43,255 DEBUG   SenderThread:706021 [sender.py:send():235] send: summary
2022-02-25 17:15:43,255 INFO    SenderThread:706021 [sender.py:_save_file():944] saving file wandb-summary.json with policy end
2022-02-25 17:15:43,256 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: run_start
2022-02-25 17:15:44,256 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/wandb-summary.json
2022-02-25 17:15:44,562 DEBUG   HandlerThread:706021 [meta.py:__init__():36] meta init
2022-02-25 17:15:44,562 DEBUG   HandlerThread:706021 [meta.py:__init__():50] meta init done
2022-02-25 17:15:44,562 DEBUG   HandlerThread:706021 [meta.py:probe():210] probe
2022-02-25 17:15:44,563 DEBUG   HandlerThread:706021 [meta.py:_setup_git():200] setup git
2022-02-25 17:15:44,580 DEBUG   HandlerThread:706021 [meta.py:_setup_git():207] setup git done
2022-02-25 17:15:44,580 DEBUG   HandlerThread:706021 [meta.py:_save_pip():54] save pip
2022-02-25 17:15:44,580 DEBUG   HandlerThread:706021 [meta.py:_save_pip():68] save pip done
2022-02-25 17:15:44,580 DEBUG   HandlerThread:706021 [meta.py:_save_conda():75] save conda
2022-02-25 17:15:45,259 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/requirements.txt
2022-02-25 17:15:45,259 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/conda-environment.yaml
2022-02-25 17:15:48,129 DEBUG   HandlerThread:706021 [meta.py:_save_conda():85] save conda done
2022-02-25 17:15:48,129 DEBUG   HandlerThread:706021 [meta.py:probe():248] probe done
2022-02-25 17:15:48,132 DEBUG   SenderThread:706021 [sender.py:send():235] send: files
2022-02-25 17:15:48,132 INFO    SenderThread:706021 [sender.py:_save_file():944] saving file wandb-metadata.json with policy now
2022-02-25 17:15:48,136 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:15:48,137 DEBUG   SenderThread:706021 [sender.py:send_request():249] send_request: stop_status
2022-02-25 17:15:48,259 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/conda-environment.yaml
2022-02-25 17:15:48,260 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/output.log
2022-02-25 17:15:48,260 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/wandb-metadata.json
2022-02-25 17:15:48,380 DEBUG   SenderThread:706021 [sender.py:send():235] send: run
2022-02-25 17:15:48,695 INFO    SenderThread:706021 [sender.py:send_run():707] updated run: yk2pvfyd
2022-02-25 17:15:49,086 INFO    Thread-11 :706021 [upload_job.py:push():137] Uploaded file /tmp/tmp2yv4befdwandb/szd78vs7-wandb-metadata.json
2022-02-25 17:15:49,260 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/config.yaml
2022-02-25 17:15:50,260 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/output.log
2022-02-25 17:15:54,812 DEBUG   SenderThread:706021 [sender.py:send():235] send: history
2022-02-25 17:15:54,812 DEBUG   SenderThread:706021 [sender.py:send():235] send: summary
2022-02-25 17:15:54,812 INFO    SenderThread:706021 [sender.py:_save_file():944] saving file wandb-summary.json with policy end
2022-02-25 17:15:55,262 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/wandb-summary.json
2022-02-25 17:15:56,262 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/output.log
2022-02-25 17:16:03,077 DEBUG   SenderThread:706021 [sender.py:send():235] send: history
2022-02-25 17:16:03,077 DEBUG   SenderThread:706021 [sender.py:send():235] send: summary
2022-02-25 17:16:03,078 INFO    SenderThread:706021 [sender.py:_save_file():944] saving file wandb-summary.json with policy end
2022-02-25 17:16:03,268 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/wandb-summary.json
2022-02-25 17:16:03,383 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:16:03,383 DEBUG   SenderThread:706021 [sender.py:send_request():249] send_request: stop_status
2022-02-25 17:16:04,269 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/output.log
2022-02-25 17:16:12,271 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/output.log
2022-02-25 17:16:20,273 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/output.log
2022-02-25 17:16:20,391 WARNING FileStreamThread:706021 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/cookie303/Assignment1/yk2pvfyd/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd8d3d6100>>, args: ('https://api.wandb.ai/files/cookie303/Assignment1/yk2pvfyd/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 0, 'content': ['2022-02-25T11:45:50.140680 epoch=1\n']}}, 'dropped': 0}}
2022-02-25 17:16:21,331 DEBUG   SenderThread:706021 [sender.py:send():235] send: history
2022-02-25 17:16:21,331 DEBUG   SenderThread:706021 [sender.py:send():235] send: summary
2022-02-25 17:16:21,332 INFO    SenderThread:706021 [sender.py:_save_file():944] saving file wandb-summary.json with policy end
2022-02-25 17:16:21,332 DEBUG   SenderThread:706021 [sender.py:send():235] send: stats
2022-02-25 17:16:21,332 DEBUG   SenderThread:706021 [sender.py:send():235] send: history
2022-02-25 17:16:21,332 DEBUG   SenderThread:706021 [sender.py:send():235] send: summary
2022-02-25 17:16:21,343 INFO    SenderThread:706021 [sender.py:_save_file():944] saving file wandb-summary.json with policy end
2022-02-25 17:16:22,274 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/wandb-summary.json
2022-02-25 17:16:23,383 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:16:23,383 DEBUG   SenderThread:706021 [sender.py:send_request():249] send_request: stop_status
2022-02-25 17:16:26,275 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/output.log
2022-02-25 17:16:34,277 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/output.log
2022-02-25 17:16:42,280 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/output.log
2022-02-25 17:16:43,383 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:16:44,281 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/output.log
2022-02-25 17:16:50,284 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/output.log
2022-02-25 17:16:56,623 ERROR   SenderThread:706021 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/sandip/anaconda3/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/home/sandip/anaconda3/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/home/sandip/anaconda3/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/sandip/anaconda3/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/home/sandip/anaconda3/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/sandip/anaconda3/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/sandip/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)
2022-02-25 17:16:58,288 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/output.log
2022-02-25 17:17:00,386 WARNING FileStreamThread:706021 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/cookie303/Assignment1/yk2pvfyd/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd8d3d6100>>, args: ('https://api.wandb.ai/files/cookie303/Assignment1/yk2pvfyd/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 0, 'content': ['2022-02-25T11:45:50.140680 epoch=1\n']}}, 'dropped': 0}}
2022-02-25 17:17:03,384 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: stop_status
2022-02-25 17:17:05,736 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:17:06,290 INFO    Thread-8  :706021 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/output.log
2022-02-25 17:17:07,014 WARNING FileStreamThread:706021 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/cookie303/Assignment1/yk2pvfyd/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd8d3d6100>>, args: ('https://api.wandb.ai/files/cookie303/Assignment1/yk2pvfyd/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 0, 'content': ['2022-02-25T11:45:50.140680 epoch=1\n']}}, 'dropped': 0}}
2022-02-25 17:17:10,837 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:17:15,938 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:17:20,289 ERROR   SenderThread:706021 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 17:17:20,290 ERROR   SenderThread:706021 [internal_api.py:execute():144] {"error":"Error 1040: Too many connections"}
2022-02-25 17:17:21,040 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:17:26,141 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:17:26,970 WARNING FileStreamThread:706021 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/cookie303/Assignment1/yk2pvfyd/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd8d3d6100>>, args: ('https://api.wandb.ai/files/cookie303/Assignment1/yk2pvfyd/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 0, 'content': ['2022-02-25T11:45:50.140680 epoch=1\n']}}, 'dropped': 0}}
2022-02-25 17:17:31,242 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:17:36,343 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:17:36,994 ERROR   SenderThread:706021 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 17:17:36,995 ERROR   SenderThread:706021 [internal_api.py:execute():144] {"error":"Error 1040: Too many connections"}
2022-02-25 17:17:41,444 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:17:46,544 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:17:51,645 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:17:56,746 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:18:01,848 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:18:06,949 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:18:12,050 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:18:17,151 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:18:22,252 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:18:27,354 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:18:32,455 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:18:37,556 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:18:42,657 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:18:47,758 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:18:47,821 WARNING FileStreamThread:706021 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/cookie303/Assignment1/yk2pvfyd/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd8d3d6100>>, args: ('https://api.wandb.ai/files/cookie303/Assignment1/yk2pvfyd/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': ['wandb-metadata.json']}}
2022-02-25 17:18:52,860 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:18:57,961 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:19:03,062 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:19:08,163 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:19:13,263 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:19:14,901 WARNING FileStreamThread:706021 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/cookie303/Assignment1/yk2pvfyd/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd8d3d6100>>, args: ('https://api.wandb.ai/files/cookie303/Assignment1/yk2pvfyd/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': ['wandb-metadata.json']}}
2022-02-25 17:19:18,365 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:19:20,586 WARNING FileStreamThread:706021 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/cookie303/Assignment1/yk2pvfyd/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd8d3d6100>>, args: ('https://api.wandb.ai/files/cookie303/Assignment1/yk2pvfyd/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': ['wandb-metadata.json']}}
2022-02-25 17:19:23,466 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:19:28,567 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:19:30,219 WARNING FileStreamThread:706021 [file_stream.py:request_with_retry():594] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/cookie303/Assignment1/yk2pvfyd/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd8d3d6100>>, args: ('https://api.wandb.ai/files/cookie303/Assignment1/yk2pvfyd/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': ['wandb-metadata.json']}}
2022-02-25 17:19:33,668 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:19:38,769 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:19:42,437 ERROR   SenderThread:706021 [internal_api.py:execute():143] 500 response executing GraphQL.
2022-02-25 17:19:42,438 ERROR   SenderThread:706021 [internal_api.py:execute():144] {"error":"Error 1040: Too many connections"}
2022-02-25 17:19:43,870 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:19:48,972 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:19:54,073 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:19:59,174 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:20:04,274 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:20:09,376 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:20:14,477 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:20:19,578 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: poll_exit
2022-02-25 17:20:24,245 WARNING MainThread:706021 [internal.py:wandb_internal():152] Internal process interrupt: 1
2022-02-25 17:20:24,579 DEBUG   HandlerThread:706021 [handler.py:handle_request():131] handle_request: shutdown
2022-02-25 17:20:24,579 INFO    HandlerThread:706021 [handler.py:finish():739] shutting down handler
2022-02-25 17:20:25,275 INFO    WriterThread:706021 [datastore.py:close():281] close: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/run-yk2pvfyd.wandb
2022-02-25 17:22:07,067 INFO    SenderThread:706021 [sender.py:finish():1075] shutting down sender
2022-02-25 17:22:07,067 INFO    SenderThread:706021 [dir_watcher.py:finish():283] shutting down directory watcher
2022-02-25 17:22:07,346 INFO    SenderThread:706021 [dir_watcher.py:finish():313] scan: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files
2022-02-25 17:22:07,346 INFO    SenderThread:706021 [dir_watcher.py:finish():327] scan save: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/config.yaml config.yaml
2022-02-25 17:22:07,346 INFO    SenderThread:706021 [dir_watcher.py:finish():327] scan save: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/requirements.txt requirements.txt
2022-02-25 17:22:07,347 INFO    SenderThread:706021 [dir_watcher.py:finish():327] scan save: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/conda-environment.yaml conda-environment.yaml
2022-02-25 17:22:07,347 INFO    SenderThread:706021 [dir_watcher.py:finish():327] scan save: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/output.log output.log
2022-02-25 17:22:07,347 INFO    SenderThread:706021 [dir_watcher.py:finish():327] scan save: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/wandb-summary.json wandb-summary.json
2022-02-25 17:22:07,347 INFO    SenderThread:706021 [dir_watcher.py:finish():327] scan save: /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/wandb-metadata.json wandb-metadata.json
2022-02-25 17:22:07,347 INFO    SenderThread:706021 [file_pusher.py:finish():177] shutting down file pusher
2022-02-25 17:22:07,347 INFO    SenderThread:706021 [file_pusher.py:join():182] waiting for file pusher
2022-02-25 17:22:08,579 INFO    Thread-16 :706021 [upload_job.py:push():137] Uploaded file /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/wandb-summary.json
2022-02-25 17:22:08,597 INFO    Thread-14 :706021 [upload_job.py:push():137] Uploaded file /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/conda-environment.yaml
2022-02-25 17:22:08,660 INFO    Thread-12 :706021 [upload_job.py:push():137] Uploaded file /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/config.yaml
2022-02-25 17:22:08,721 INFO    Thread-15 :706021 [upload_job.py:push():137] Uploaded file /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/output.log
2022-02-25 17:22:08,810 INFO    Thread-13 :706021 [upload_job.py:push():137] Uploaded file /home/sandip/Desktop/DL/Assignment 1/wandb/run-20220225_171542-yk2pvfyd/files/requirements.txt
2022-02-25 17:22:10,163 INFO    MainThread:706021 [internal.py:handle_exit():79] Internal process exited
